import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Day 1: Prompt Engineering',
      link: {
        type: 'doc',
        id: 'day1/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'day1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Day 2: n8n Automation',
      link: {
        type: 'doc',
        id: 'day2/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'day2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Day 3: AI Deployment',
      link: {
        type: 'doc',
        id: 'day3/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'day3',
        },
      ],
    },
  ],
};

export default sidebars;
